name: PR Validation

on:
  pull_request:
    branches: [ main, master, sugnana01 ]
    

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: write

jobs:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/checkout@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: uild and runtests
      uses: mvn clean test
